//VSCode RestClient extension for testing REST requests

POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "video 01",
    "description": "Esse é o primeiro video",
    "duration": 180
}


###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/011b645d-a118-4625-922a-d261f825d132
Content-Type: application/json

{
    "title": "video 02",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE  http://localhost:3333/videos/df2342c5-62fd-47a2-a639-9f2122493e51